services:
  api-mlflow:
    build:
      dockerfile: docker/api-mlflow/Dockerfile
    ports:
      - 8000:8000
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}